### ISSUE TITLE
Arrow Filter Pushdown on TIMESTAMP

### ISSUE THREAD

**Issue by spren9er** [red-data-tools/red-arrow-duckdb#2]
When I run queries with timestamp comparisons in WHERE clause like (_table_ is an Arrow table)

```sql
SELECT passenger_count, COUNT(*) AS total
FROM 'table'
WHERE pickup_at < '2015-01-01'
GROUP BY passenger_count
```

following exception is raised:

_Not implemented Error: [arrow][filter][pushdown] not implemented value type: TIMESTAMP (DuckDB::Error)_

Support of timestamps is commented out [here](https://github.com/red-data-tools/red-arrow-duckdb/blob/924a8d5706889e406c9e5b058e5c8a820806eabd/ext/arrow-duckdb/arrow-duckdb-registration.cpp#L58). Also some other data types are left out.

Is there a reason for this? 
Doesn't filter pushdown work for timestamps, dates, etc.?

**Comment by kou** [comment]
I don't remember why I didn't implement it... Maybe, timestamp unit is unknown when I implemented it...

Now, DuckDB has timestamp types for all units. I've implemented this.

**Comment by spren9er** [comment]
Great, thanks for prompt support!
